package dev.eiersohn.sm64cross.client.bridge;

import com.google.gson.JsonObject;
import dev.eiersohn.sm64cross.client.render.Sm64VisualSync;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.ChatScreen;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.screens.inventory.InventoryScreen;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.network.protocol.game.ServerboundPlayerActionPacket;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.EntityHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import org.lwjgl.glfw.GLFW;

/**
 * Commands generated by the visible SM64 host for the hidden Minecraft guest.
 *
 * Hotbar selection and inventory interaction therefore continue to work even
 * though the Minecraft GLFW window has no keyboard/mouse focus.
 */
public final class GuestCommandHandler {
    private static long lastLeftSerial = -1L;
    private static long lastRightSerial = -1L;
    private static boolean leftDown;
    private static boolean rightDown;
    private static double lastGuiX;
    private static double lastGuiY;
    private static long lastAttackAction = -1L;
    private static long lastUseAction = -1L;
    private static boolean destroyingBlock;
    private static boolean usingItem;

    private GuestCommandHandler() {
    }

    public static void handle(JsonObject message) {
        String type = message.get("t").getAsString();

        switch (type) {
            case "slot" -> selectSlot(message.get("slot").getAsInt());
            case "inventory" -> toggleInventory();
            case "pointer" -> pointer(message);
            case "action" -> gameplayAction(message);
            case "drop" -> dropItem(message);
            case "swap" -> swapOffhand();
            case "escape" -> closeScreen();
            case "chat" -> openChat(false);
            case "command" -> openChat(true);
            case "key" -> keyboard(message);
            case "terrain_begin" -> Sm64TerrainProxy.begin();
            case "terrain" -> Sm64TerrainProxy.cell(
                    message.get("x").getAsInt(),
                    message.get("y").getAsInt(),
                    message.get("z").getAsInt()
            );
            case "terrain_end" -> Sm64TerrainProxy.end();
            default -> {
            }
        }
    }

    private static void selectSlot(int slot) {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null) {
                return;
            }

            client.player.getInventory().selected =
                    Math.max(0, Math.min(8, slot));
        });
    }

    private static void toggleInventory() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null) {
                return;
            }

            if (client.screen == null) {
                client.setScreen(new InventoryScreen(client.player));
            } else {
                client.setScreen(null);
            }
        });
    }

    private static void pointer(JsonObject message) {
        final double nx = clamp01(message.get("x").getAsDouble());
        final double ny = clamp01(message.get("y").getAsDouble());
        final long leftSerial = message.get("left").getAsLong();
        final long rightSerial = message.get("right").getAsLong();
        final boolean newLeftDown = message.get("ld").getAsInt() != 0;
        final boolean newRightDown = message.get("rd").getAsInt() != 0;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            Screen screen = client.screen;
            if (screen == null) {
                leftDown = newLeftDown;
                rightDown = newRightDown;
                lastLeftSerial = leftSerial;
                lastRightSerial = rightSerial;
                return;
            }

            double guiX =
                    nx * client.getWindow().getGuiScaledWidth();
            double guiY =
                    ny * client.getWindow().getGuiScaledHeight();

            /*
             * Keep vanilla hover/tooltips aligned with the actual cursor in
             * the visible SM64 window.
             */
            GLFW.glfwSetCursorPos(
                    client.getWindow().getWindow(),
                    nx * client.getWindow().getScreenWidth(),
                    ny * client.getWindow().getScreenHeight()
            );

            screen.mouseMoved(guiX, guiY);

            double dx = guiX - lastGuiX;
            double dy = guiY - lastGuiY;

            if (leftDown && newLeftDown) {
                screen.mouseDragged(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT,
                        dx,
                        dy
                );
            }
            if (rightDown && newRightDown) {
                screen.mouseDragged(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT,
                        dx,
                        dy
                );
            }

            if (leftSerial != lastLeftSerial && newLeftDown) {
                screen.mouseClicked(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT
                );
            }
            if (rightSerial != lastRightSerial && newRightDown) {
                screen.mouseClicked(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT
                );
            }

            if (leftDown && !newLeftDown) {
                screen.mouseReleased(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT
                );
            }
            if (rightDown && !newRightDown) {
                screen.mouseReleased(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT
                );
            }

            leftDown = newLeftDown;
            rightDown = newRightDown;
            lastLeftSerial = leftSerial;
            lastRightSerial = rightSerial;
            lastGuiX = guiX;
            lastGuiY = guiY;
        });
    }

    private static void dropItem(JsonObject message) {
        Minecraft client = Minecraft.getInstance();
        final boolean stack =
                message.has("stack")
                && message.get("stack").getAsInt() != 0;

        client.execute(() -> {
            if (client.player != null
                    && client.screen == null
                    && !client.player.isSpectator()) {
                client.player.drop(stack);
            }
        });
    }

    private static void swapOffhand() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null || client.screen != null) {
                return;
            }

            client.player.connection.send(
                    new ServerboundPlayerActionPacket(
                            ServerboundPlayerActionPacket.Action
                                    .SWAP_ITEM_WITH_OFFHAND,
                            BlockPos.ZERO,
                            Direction.DOWN
                    )
            );
        });
    }

    private static void closeScreen() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.screen != null) {
                client.setScreen(null);
            }
        });
    }

    private static void openChat(boolean command) {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player != null && client.screen == null) {
                client.setScreen(
                        new ChatScreen(command ? "/" : "")
                );
            }
        });
    }

    private static void keyboard(JsonObject message) {
        final int virtualKey = message.get("vk").getAsInt();
        final boolean down = message.get("down").getAsInt() != 0;
        final int modifiers = message.has("mods")
                ? message.get("mods").getAsInt()
                : 0;
        final int codePoint = message.has("cp")
                ? message.get("cp").getAsInt()
                : 0;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            Screen screen = client.screen;
            if (screen == null) {
                return;
            }

            int key = glfwKey(virtualKey);
            if (key != GLFW.GLFW_KEY_UNKNOWN) {
                if (down) {
                    screen.keyPressed(key, 0, modifiers);
                } else {
                    screen.keyReleased(key, 0, modifiers);
                }
            }

            if (down && codePoint > 0) {
                if (Character.isBmpCodePoint(codePoint)) {
                    screen.charTyped((char) codePoint, modifiers);
                } else if (Character.isValidCodePoint(codePoint)) {
                    screen.charTyped(
                            Character.highSurrogate(codePoint),
                            modifiers
                    );
                    screen.charTyped(
                            Character.lowSurrogate(codePoint),
                            modifiers
                    );
                }
            }
        });
    }

    private static int glfwKey(int vk) {
        if ((vk >= '0' && vk <= '9')
                || (vk >= 'A' && vk <= 'Z')) {
            return vk;
        }

        return switch (vk) {
            case 0x20 -> GLFW.GLFW_KEY_SPACE;
            case 0x1B -> GLFW.GLFW_KEY_ESCAPE;
            case 0x0D -> GLFW.GLFW_KEY_ENTER;
            case 0x09 -> GLFW.GLFW_KEY_TAB;
            case 0x08 -> GLFW.GLFW_KEY_BACKSPACE;
            case 0x2D -> GLFW.GLFW_KEY_INSERT;
            case 0x2E -> GLFW.GLFW_KEY_DELETE;
            case 0x27 -> GLFW.GLFW_KEY_RIGHT;
            case 0x25 -> GLFW.GLFW_KEY_LEFT;
            case 0x28 -> GLFW.GLFW_KEY_DOWN;
            case 0x26 -> GLFW.GLFW_KEY_UP;
            case 0x21 -> GLFW.GLFW_KEY_PAGE_UP;
            case 0x22 -> GLFW.GLFW_KEY_PAGE_DOWN;
            case 0x24 -> GLFW.GLFW_KEY_HOME;
            case 0x23 -> GLFW.GLFW_KEY_END;
            case 0x14 -> GLFW.GLFW_KEY_CAPS_LOCK;
            case 0x91 -> GLFW.GLFW_KEY_SCROLL_LOCK;
            case 0x90 -> GLFW.GLFW_KEY_NUM_LOCK;
            case 0x2C -> GLFW.GLFW_KEY_PRINT_SCREEN;
            case 0x13 -> GLFW.GLFW_KEY_PAUSE;

            // Windows OEM keys. charTyped carries the layout-specific text;
            // these codes are mainly needed for navigation/keybind handling.
            case 0xBA -> GLFW.GLFW_KEY_SEMICOLON;
            case 0xBB -> GLFW.GLFW_KEY_EQUAL;
            case 0xBC -> GLFW.GLFW_KEY_COMMA;
            case 0xBD -> GLFW.GLFW_KEY_MINUS;
            case 0xBE -> GLFW.GLFW_KEY_PERIOD;
            case 0xBF -> GLFW.GLFW_KEY_SLASH;
            case 0xC0 -> GLFW.GLFW_KEY_GRAVE_ACCENT;
            case 0xDB -> GLFW.GLFW_KEY_LEFT_BRACKET;
            case 0xDC -> GLFW.GLFW_KEY_BACKSLASH;
            case 0xDD -> GLFW.GLFW_KEY_RIGHT_BRACKET;
            case 0xDE -> GLFW.GLFW_KEY_APOSTROPHE;

            case 0xA0 -> GLFW.GLFW_KEY_LEFT_SHIFT;
            case 0xA1 -> GLFW.GLFW_KEY_RIGHT_SHIFT;
            case 0xA2 -> GLFW.GLFW_KEY_LEFT_CONTROL;
            case 0xA3 -> GLFW.GLFW_KEY_RIGHT_CONTROL;
            case 0xA4 -> GLFW.GLFW_KEY_LEFT_ALT;
            case 0xA5 -> GLFW.GLFW_KEY_RIGHT_ALT;
            case 0x5B -> GLFW.GLFW_KEY_LEFT_SUPER;
            case 0x5C -> GLFW.GLFW_KEY_RIGHT_SUPER;

            default -> {
                if (vk >= 0x70 && vk <= 0x7B) {
                    yield GLFW.GLFW_KEY_F1 + (vk - 0x70);
                }
                yield GLFW.GLFW_KEY_UNKNOWN;
            }
        };
    }

    private static void gameplayAction(JsonObject message) {
        final long attackSerial =
                message.get("attack").getAsLong();
        final long useSerial =
                message.get("use").getAsLong();
        final boolean attackDown =
                message.get("ad").getAsInt() != 0;
        final boolean useDown =
                message.get("ud").getAsInt() != 0;
        final boolean hostHit =
                message.has("hit")
                && message.get("hit").getAsInt() != 0;

        final double hitX = hostHit
                ? message.getAsJsonArray("p").get(0).getAsDouble()
                : 0.0;
        final double hitY = hostHit
                ? message.getAsJsonArray("p").get(1).getAsDouble()
                : 0.0;
        final double hitZ = hostHit
                ? message.getAsJsonArray("p").get(2).getAsDouble()
                : 0.0;

        final float normalX = hostHit
                ? message.getAsJsonArray("n").get(0).getAsFloat()
                : 0.0f;
        final float normalY = hostHit
                ? message.getAsJsonArray("n").get(1).getAsFloat()
                : 1.0f;
        final float normalZ = hostHit
                ? message.getAsJsonArray("n").get(2).getAsFloat()
                : 0.0f;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null
                    || client.level == null
                    || client.gameMode == null
                    || client.screen != null) {
                return;
            }

            HitResult target = client.hitResult;

            if (attackSerial != lastAttackAction && attackDown) {
                lastAttackAction = attackSerial;

                if (target instanceof EntityHitResult entityHit) {
                    Entity entity = entityHit.getEntity();
                    client.gameMode.attack(client.player, entity);
                    client.player.swing(InteractionHand.MAIN_HAND);
                } else if (target instanceof BlockHitResult blockHit
                        && target.getType() == HitResult.Type.BLOCK) {
                    destroyingBlock = client.gameMode.startDestroyBlock(
                            blockHit.getBlockPos(),
                            blockHit.getDirection()
                    );
                    client.player.swing(InteractionHand.MAIN_HAND);
                }
            }

            if (attackDown
                    && destroyingBlock
                    && target instanceof BlockHitResult blockHit
                    && target.getType() == HitResult.Type.BLOCK) {
                client.gameMode.continueDestroyBlock(
                        blockHit.getBlockPos(),
                        blockHit.getDirection()
                );
            } else if (!attackDown && destroyingBlock) {
                client.gameMode.stopDestroyBlock();
                destroyingBlock = false;
            }

            if (useSerial != lastUseAction && useDown) {
                lastUseAction = useSerial;

                boolean handled = false;

                if (target instanceof EntityHitResult entityHit) {
                    client.gameMode.interact(
                            client.player,
                            entityHit.getEntity(),
                            InteractionHand.MAIN_HAND
                    );
                    handled = true;
                } else if (target instanceof BlockHitResult blockHit
                        && target.getType() == HitResult.Type.BLOCK) {
                    client.gameMode.useItemOn(
                            client.player,
                            InteractionHand.MAIN_HAND,
                            blockHit
                    );
                    handled = true;
                }

                if (!handled && hostHit) {
                    /*
                     * SM64 supplied a hit against its real triangle collision.
                     * Convert that point into the hidden Minecraft overlay
                     * world's block grid. The +normal*0.55 offset picks the
                     * voxel immediately outside the SM64 surface.
                     */
                    double placeX = hitX + normalX * 0.55;
                    double placeY =
                            Sm64VisualSync.renderY(
                                    hitY + normalY * 0.55
                            );
                    double placeZ = hitZ + normalZ * 0.55;

                    BlockPos placePos = BlockPos.containing(
                            placeX,
                            placeY,
                            placeZ
                    );
                    Direction face = Direction.getNearest(
                            normalX,
                            normalY,
                            normalZ
                    );

                    BlockHitResult synthetic =
                            new BlockHitResult(
                                    new Vec3(
                                            placeX,
                                            placeY,
                                            placeZ
                                    ),
                                    face,
                                    placePos,
                                    false
                            );

                    client.gameMode.useItemOn(
                            client.player,
                            InteractionHand.MAIN_HAND,
                            synthetic
                    );
                    handled = true;
                }

                if (!handled) {
                    client.gameMode.useItem(
                            client.player,
                            InteractionHand.MAIN_HAND
                    );
                }

                client.player.swing(InteractionHand.MAIN_HAND);
                usingItem = true;
            }

            if (!useDown && usingItem) {
                client.gameMode.releaseUsingItem(client.player);
                usingItem = false;
            }
        });
    }

    private static double clamp01(double value) {
        return Math.max(0.0, Math.min(1.0, value));
    }
}
