package dev.eiersohn.sm64cross.client.bridge;

import com.google.gson.JsonObject;
import dev.eiersohn.sm64cross.client.render.Sm64VisualSync;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.screens.inventory.InventoryScreen;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.network.protocol.game.ServerboundPlayerActionPacket;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.EntityHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import org.lwjgl.glfw.GLFW;

/**
 * Commands generated by the visible SM64 host for the hidden Minecraft guest.
 *
 * Hotbar selection and inventory interaction therefore continue to work even
 * though the Minecraft GLFW window has no keyboard/mouse focus.
 */
public final class GuestCommandHandler {
    private static long lastLeftSerial = -1L;
    private static long lastRightSerial = -1L;
    private static boolean leftDown;
    private static boolean rightDown;
    private static double lastGuiX;
    private static double lastGuiY;
    private static long lastAttackAction = -1L;
    private static long lastUseAction = -1L;
    private static boolean destroyingBlock;
    private static boolean usingItem;

    private GuestCommandHandler() {
    }

    public static void handle(JsonObject message) {
        String type = message.get("t").getAsString();

        switch (type) {
            case "slot" -> selectSlot(message.get("slot").getAsInt());
            case "inventory" -> toggleInventory();
            case "pointer" -> pointer(message);
            case "action" -> gameplayAction(message);
            case "drop" -> dropItem(message);
            case "swap" -> swapOffhand();
            case "escape" -> closeScreen();
            default -> {
            }
        }
    }

    private static void selectSlot(int slot) {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null) {
                return;
            }

            client.player.getInventory().selected =
                    Math.max(0, Math.min(8, slot));
        });
    }

    private static void toggleInventory() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null) {
                return;
            }

            if (client.screen instanceof InventoryScreen) {
                client.setScreen(null);
            } else {
                client.setScreen(new InventoryScreen(client.player));
            }
        });
    }

    private static void pointer(JsonObject message) {
        final double nx = clamp01(message.get("x").getAsDouble());
        final double ny = clamp01(message.get("y").getAsDouble());
        final long leftSerial = message.get("left").getAsLong();
        final long rightSerial = message.get("right").getAsLong();
        final boolean newLeftDown = message.get("ld").getAsInt() != 0;
        final boolean newRightDown = message.get("rd").getAsInt() != 0;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            Screen screen = client.screen;
            if (screen == null) {
                leftDown = newLeftDown;
                rightDown = newRightDown;
                lastLeftSerial = leftSerial;
                lastRightSerial = rightSerial;
                return;
            }

            double guiX =
                    nx * client.getWindow().getGuiScaledWidth();
            double guiY =
                    ny * client.getWindow().getGuiScaledHeight();

            /*
             * Keep vanilla hover/tooltips aligned with the actual cursor in
             * the visible SM64 window.
             */
            GLFW.glfwSetCursorPos(
                    client.getWindow().getWindow(),
                    nx * client.getWindow().getScreenWidth(),
                    ny * client.getWindow().getScreenHeight()
            );

            screen.mouseMoved(guiX, guiY);

            double dx = guiX - lastGuiX;
            double dy = guiY - lastGuiY;

            if (leftDown && newLeftDown) {
                screen.mouseDragged(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT,
                        dx,
                        dy
                );
            }
            if (rightDown && newRightDown) {
                screen.mouseDragged(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT,
                        dx,
                        dy
                );
            }

            if (leftSerial != lastLeftSerial && newLeftDown) {
                screen.mouseClicked(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT
                );
            }
            if (rightSerial != lastRightSerial && newRightDown) {
                screen.mouseClicked(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT
                );
            }

            if (leftDown && !newLeftDown) {
                screen.mouseReleased(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT
                );
            }
            if (rightDown && !newRightDown) {
                screen.mouseReleased(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT
                );
            }

            leftDown = newLeftDown;
            rightDown = newRightDown;
            lastLeftSerial = leftSerial;
            lastRightSerial = rightSerial;
            lastGuiX = guiX;
            lastGuiY = guiY;
        });
    }

    private static void dropItem(JsonObject message) {
        Minecraft client = Minecraft.getInstance();
        final boolean stack =
                message.has("stack")
                && message.get("stack").getAsInt() != 0;

        client.execute(() -> {
            if (client.player != null
                    && client.screen == null
                    && !client.player.isSpectator()) {
                client.player.drop(stack);
            }
        });
    }

    private static void swapOffhand() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null || client.screen != null) {
                return;
            }

            client.player.connection.send(
                    new ServerboundPlayerActionPacket(
                            ServerboundPlayerActionPacket.Action
                                    .SWAP_ITEM_WITH_OFFHAND,
                            BlockPos.ZERO,
                            Direction.DOWN
                    )
            );
        });
    }

    private static void closeScreen() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.screen != null) {
                client.setScreen(null);
            }
        });
    }

    private static void gameplayAction(JsonObject message) {
        final long attackSerial =
                message.get("attack").getAsLong();
        final long useSerial =
                message.get("use").getAsLong();
        final boolean attackDown =
                message.get("ad").getAsInt() != 0;
        final boolean useDown =
                message.get("ud").getAsInt() != 0;
        final boolean hostHit =
                message.has("hit")
                && message.get("hit").getAsInt() != 0;

        final double hitX = hostHit
                ? message.getAsJsonArray("p").get(0).getAsDouble()
                : 0.0;
        final double hitY = hostHit
                ? message.getAsJsonArray("p").get(1).getAsDouble()
                : 0.0;
        final double hitZ = hostHit
                ? message.getAsJsonArray("p").get(2).getAsDouble()
                : 0.0;

        final float normalX = hostHit
                ? message.getAsJsonArray("n").get(0).getAsFloat()
                : 0.0f;
        final float normalY = hostHit
                ? message.getAsJsonArray("n").get(1).getAsFloat()
                : 1.0f;
        final float normalZ = hostHit
                ? message.getAsJsonArray("n").get(2).getAsFloat()
                : 0.0f;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null
                    || client.level == null
                    || client.gameMode == null
                    || client.screen != null) {
                return;
            }

            HitResult target = client.hitResult;

            if (attackSerial != lastAttackAction && attackDown) {
                lastAttackAction = attackSerial;

                if (target instanceof EntityHitResult entityHit) {
                    Entity entity = entityHit.getEntity();
                    client.gameMode.attack(client.player, entity);
                    client.player.swing(InteractionHand.MAIN_HAND);
                } else if (target instanceof BlockHitResult blockHit
                        && target.getType() == HitResult.Type.BLOCK) {
                    destroyingBlock = client.gameMode.startDestroyBlock(
                            blockHit.getBlockPos(),
                            blockHit.getDirection()
                    );
                    client.player.swing(InteractionHand.MAIN_HAND);
                }
            }

            if (attackDown
                    && destroyingBlock
                    && target instanceof BlockHitResult blockHit
                    && target.getType() == HitResult.Type.BLOCK) {
                client.gameMode.continueDestroyBlock(
                        blockHit.getBlockPos(),
                        blockHit.getDirection()
                );
            } else if (!attackDown && destroyingBlock) {
                client.gameMode.stopDestroyBlock();
                destroyingBlock = false;
            }

            if (useSerial != lastUseAction && useDown) {
                lastUseAction = useSerial;

                boolean handled = false;

                if (target instanceof EntityHitResult entityHit) {
                    client.gameMode.interact(
                            client.player,
                            entityHit.getEntity(),
                            InteractionHand.MAIN_HAND
                    );
                    handled = true;
                } else if (target instanceof BlockHitResult blockHit
                        && target.getType() == HitResult.Type.BLOCK) {
                    client.gameMode.useItemOn(
                            client.player,
                            InteractionHand.MAIN_HAND,
                            blockHit
                    );
                    handled = true;
                }

                if (!handled && hostHit) {
                    /*
                     * SM64 supplied a hit against its real triangle collision.
                     * Convert that point into the hidden Minecraft overlay
                     * world's block grid. The +normal*0.55 offset picks the
                     * voxel immediately outside the SM64 surface.
                     */
                    double placeX = hitX + normalX * 0.55;
                    double placeY =
                            Sm64VisualSync.renderY(
                                    hitY + normalY * 0.55
                            );
                    double placeZ = hitZ + normalZ * 0.55;

                    BlockPos placePos = BlockPos.containing(
                            placeX,
                            placeY,
                            placeZ
                    );
                    Direction face = Direction.getNearest(
                            normalX,
                            normalY,
                            normalZ
                    );

                    BlockHitResult synthetic =
                            new BlockHitResult(
                                    new Vec3(
                                            placeX,
                                            placeY,
                                            placeZ
                                    ),
                                    face,
                                    placePos,
                                    false
                            );

                    client.gameMode.useItemOn(
                            client.player,
                            InteractionHand.MAIN_HAND,
                            synthetic
                    );
                    handled = true;
                }

                if (!handled) {
                    client.gameMode.useItem(
                            client.player,
                            InteractionHand.MAIN_HAND
                    );
                }

                client.player.swing(InteractionHand.MAIN_HAND);
                usingItem = true;
            }

            if (!useDown && usingItem) {
                client.gameMode.releaseUsingItem(client.player);
                usingItem = false;
            }
        });
    }

    private static double clamp01(double value) {
        return Math.max(0.0, Math.min(1.0, value));
    }
}
