package dev.eiersohn.sm64cross.client.bridge;

import com.google.gson.JsonObject;
import dev.eiersohn.sm64cross.client.render.Sm64VisualSync;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.ChatScreen;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen;
import net.minecraft.client.gui.screens.inventory.InventoryScreen;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.network.protocol.game.ServerboundPlayerActionPacket;
import net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.EntityHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import org.lwjgl.glfw.GLFW;

/**
 * Commands generated by the visible SM64 host for the hidden Minecraft guest.
 *
 * Hotbar selection and inventory interaction therefore continue to work even
 * though the Minecraft GLFW window has no keyboard/mouse focus.
 */
public final class GuestCommandHandler {
    private static long lastLeftSerial = -1L;
    private static long lastRightSerial = -1L;
    private static boolean leftDown;
    private static boolean rightDown;
    private static double lastGuiX;
    private static double lastGuiY;
    private static long lastAttackAction = -1L;
    private static long lastUseAction = -1L;
    private static boolean destroyingBlock;
    private static BlockPos destroyingPos;
    private static Direction destroyingFace;
    private static boolean usingItem;

    private GuestCommandHandler() {
    }

    public static void handle(JsonObject message) {
        String type = message.get("t").getAsString();

        switch (type) {
            case "slot" -> selectSlot(message.get("slot").getAsInt());
            case "scroll" -> scrollHotbar(
                    message.get("delta").getAsInt()
            );
            case "inventory" -> toggleInventory();
            case "hud" -> toggleHud();
            case "move" -> movementInput(message);
            case "look" -> mouseLook(message);
            case "pointer" -> pointer(message);
            case "action" -> gameplayAction(message);
            case "drop" -> dropItem(message);
            case "swap" -> swapOffhand();
            case "escape" -> closeScreen();
            case "chat" -> openChat(false);
            case "command" -> openChat(true);
            case "key" -> keyboard(message);
            case "terrain_begin" -> Sm64TerrainProxy.begin();
            case "terrain" -> Sm64TerrainProxy.cell(
                    message.get("x").getAsInt(),
                    message.get("y").getAsInt(),
                    message.get("z").getAsInt()
            );
            case "terrain_end" -> Sm64TerrainProxy.end();
            default -> {
            }
        }
    }

    private static void movementInput(JsonObject message) {
        final boolean forward = message.get("f").getAsInt() != 0;
        final boolean back = message.get("b").getAsInt() != 0;
        final boolean left = message.get("l").getAsInt() != 0;
        final boolean right = message.get("r").getAsInt() != 0;
        final boolean jump = message.get("jump").getAsInt() != 0;
        final boolean sneak = message.get("sneak").getAsInt() != 0;
        final boolean sprint = message.get("sprint").getAsInt() != 0;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> setMovementKeys(
                client,
                forward,
                back,
                left,
                right,
                jump,
                sneak,
                sprint
        ));
    }

    /**
     * Apply the visible host's raw mouse delta through Minecraft's own
     * sensitivity curve. Minecraft remains authoritative for yaw/pitch; the
     * SM64 camera only mirrors the resulting player rotation.
     */
    private static void mouseLook(JsonObject message) {
        final double dx = message.get("dx").getAsDouble();
        final double dy = message.get("dy").getAsDouble();

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null || client.screen != null) {
                return;
            }

            double sensitivity = client.options.sensitivity().get();
            double scale = sensitivity * 0.6 + 0.2;
            double vanillaMouseScale = scale * scale * scale * 8.0;
            double invertY =
                    client.options.invertYMouse().get() ? -1.0 : 1.0;

            client.player.turn(
                    dx * vanillaMouseScale,
                    dy * vanillaMouseScale * invertY
            );
            client.player.setYHeadRot(client.player.getYRot());
        });
    }

    public static void releaseMovement() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> setMovementKeys(
                client,
                false, false, false, false,
                false, false, false
        ));
    }

    private static void setMovementKeys(
            Minecraft client,
            boolean forward,
            boolean back,
            boolean left,
            boolean right,
            boolean jump,
            boolean sneak,
            boolean sprint
    ) {
        client.options.keyUp.setDown(forward);
        client.options.keyDown.setDown(back);
        client.options.keyLeft.setDown(left);
        client.options.keyRight.setDown(right);
        client.options.keyJump.setDown(jump);
        client.options.keyShift.setDown(sneak);
        client.options.keySprint.setDown(sprint);
    }

    private static void selectSlot(int slot) {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null) {
                return;
            }

            int selected = Math.max(0, Math.min(8, slot));
            client.player.getInventory().selected = selected;
            client.player.connection.send(
                    new ServerboundSetCarriedItemPacket(selected)
            );
        });
    }

    private static void scrollHotbar(int delta) {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null
                    || client.screen != null
                    || delta == 0) {
                return;
            }

            int step = Integer.signum(delta);
            int selected =
                    Math.floorMod(
                            client.player.getInventory().selected
                                    - step,
                            9
                    );

            client.player.getInventory().selected = selected;
            client.player.connection.send(
                    new ServerboundSetCarriedItemPacket(selected)
            );
        });
    }

    private static void toggleHud() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() ->
                client.options.hideGui = !client.options.hideGui
        );
    }

    private static void toggleInventory() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null) {
                return;
            }

            if (client.screen != null) {
                client.setScreen(null);
                return;
            }

            if (client.gameMode != null
                    && client.gameMode.hasInfiniteItems()) {
                client.setScreen(
                        new CreativeModeInventoryScreen(
                                client.player,
                                client.player.connection.enabledFeatures(),
                                client.options.operatorItemsTab().get()
                        )
                );
            } else {
                client.setScreen(
                        new InventoryScreen(client.player)
                );
            }
        });
    }

    private static void pointer(JsonObject message) {
        final double nx = clamp01(message.get("x").getAsDouble());
        final double ny = clamp01(message.get("y").getAsDouble());
        final long leftSerial = message.get("left").getAsLong();
        final long rightSerial = message.get("right").getAsLong();
        final boolean newLeftDown = message.get("ld").getAsInt() != 0;
        final boolean newRightDown = message.get("rd").getAsInt() != 0;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            Screen screen = client.screen;
            if (screen == null) {
                leftDown = newLeftDown;
                rightDown = newRightDown;
                lastLeftSerial = leftSerial;
                lastRightSerial = rightSerial;
                return;
            }

            double guiX =
                    nx * client.getWindow().getGuiScaledWidth();
            double guiY =
                    ny * client.getWindow().getGuiScaledHeight();

            /*
             * Keep vanilla hover/tooltips aligned with the actual cursor in
             * the visible SM64 window.
             */
            GLFW.glfwSetCursorPos(
                    client.getWindow().getWindow(),
                    nx * client.getWindow().getScreenWidth(),
                    ny * client.getWindow().getScreenHeight()
            );

            screen.mouseMoved(guiX, guiY);

            double dx = guiX - lastGuiX;
            double dy = guiY - lastGuiY;

            if (leftDown && newLeftDown) {
                screen.mouseDragged(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT,
                        dx,
                        dy
                );
            }
            if (rightDown && newRightDown) {
                screen.mouseDragged(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT,
                        dx,
                        dy
                );
            }

            if (leftSerial != lastLeftSerial && newLeftDown) {
                screen.mouseClicked(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT
                );
            }
            if (rightSerial != lastRightSerial && newRightDown) {
                screen.mouseClicked(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT
                );
            }

            if (leftDown && !newLeftDown) {
                screen.mouseReleased(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_LEFT
                );
            }
            if (rightDown && !newRightDown) {
                screen.mouseReleased(
                        guiX,
                        guiY,
                        GLFW.GLFW_MOUSE_BUTTON_RIGHT
                );
            }

            leftDown = newLeftDown;
            rightDown = newRightDown;
            lastLeftSerial = leftSerial;
            lastRightSerial = rightSerial;
            lastGuiX = guiX;
            lastGuiY = guiY;
        });
    }

    private static void dropItem(JsonObject message) {
        Minecraft client = Minecraft.getInstance();
        final boolean stack =
                message.has("stack")
                && message.get("stack").getAsInt() != 0;

        client.execute(() -> {
            if (client.player != null
                    && client.screen == null
                    && !client.player.isSpectator()) {
                client.player.drop(stack);
            }
        });
    }

    private static void swapOffhand() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null || client.screen != null) {
                return;
            }

            client.player.connection.send(
                    new ServerboundPlayerActionPacket(
                            ServerboundPlayerActionPacket.Action
                                    .SWAP_ITEM_WITH_OFFHAND,
                            BlockPos.ZERO,
                            Direction.DOWN
                    )
            );
        });
    }

    private static void closeScreen() {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.screen != null) {
                client.setScreen(null);
            }
        });
    }

    private static void openChat(boolean command) {
        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player != null && client.screen == null) {
                client.setScreen(
                        new ChatScreen(command ? "/" : "")
                );
            }
        });
    }

    private static void keyboard(JsonObject message) {
        final int virtualKey = message.get("vk").getAsInt();
        final boolean down = message.get("down").getAsInt() != 0;
        final int modifiers = message.has("mods")
                ? message.get("mods").getAsInt()
                : 0;
        final int codePoint = message.has("cp")
                ? message.get("cp").getAsInt()
                : 0;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            Screen screen = client.screen;
            if (screen == null) {
                return;
            }

            int key = glfwKey(virtualKey);
            if (key != GLFW.GLFW_KEY_UNKNOWN) {
                if (down) {
                    screen.keyPressed(key, 0, modifiers);
                } else {
                    screen.keyReleased(key, 0, modifiers);
                }
            }

            if (down && codePoint > 0) {
                if (Character.isBmpCodePoint(codePoint)) {
                    screen.charTyped((char) codePoint, modifiers);
                } else if (Character.isValidCodePoint(codePoint)) {
                    screen.charTyped(
                            Character.highSurrogate(codePoint),
                            modifiers
                    );
                    screen.charTyped(
                            Character.lowSurrogate(codePoint),
                            modifiers
                    );
                }
            }
        });
    }

    private static int glfwKey(int vk) {
        if ((vk >= '0' && vk <= '9')
                || (vk >= 'A' && vk <= 'Z')) {
            return vk;
        }

        return switch (vk) {
            case 0x20 -> GLFW.GLFW_KEY_SPACE;
            case 0x1B -> GLFW.GLFW_KEY_ESCAPE;
            case 0x0D -> GLFW.GLFW_KEY_ENTER;
            case 0x09 -> GLFW.GLFW_KEY_TAB;
            case 0x08 -> GLFW.GLFW_KEY_BACKSPACE;
            case 0x2D -> GLFW.GLFW_KEY_INSERT;
            case 0x2E -> GLFW.GLFW_KEY_DELETE;
            case 0x27 -> GLFW.GLFW_KEY_RIGHT;
            case 0x25 -> GLFW.GLFW_KEY_LEFT;
            case 0x28 -> GLFW.GLFW_KEY_DOWN;
            case 0x26 -> GLFW.GLFW_KEY_UP;
            case 0x21 -> GLFW.GLFW_KEY_PAGE_UP;
            case 0x22 -> GLFW.GLFW_KEY_PAGE_DOWN;
            case 0x24 -> GLFW.GLFW_KEY_HOME;
            case 0x23 -> GLFW.GLFW_KEY_END;
            case 0x14 -> GLFW.GLFW_KEY_CAPS_LOCK;
            case 0x91 -> GLFW.GLFW_KEY_SCROLL_LOCK;
            case 0x90 -> GLFW.GLFW_KEY_NUM_LOCK;
            case 0x2C -> GLFW.GLFW_KEY_PRINT_SCREEN;
            case 0x13 -> GLFW.GLFW_KEY_PAUSE;

            // Windows OEM keys. charTyped carries the layout-specific text;
            // these codes are mainly needed for navigation/keybind handling.
            case 0xBA -> GLFW.GLFW_KEY_SEMICOLON;
            case 0xBB -> GLFW.GLFW_KEY_EQUAL;
            case 0xBC -> GLFW.GLFW_KEY_COMMA;
            case 0xBD -> GLFW.GLFW_KEY_MINUS;
            case 0xBE -> GLFW.GLFW_KEY_PERIOD;
            case 0xBF -> GLFW.GLFW_KEY_SLASH;
            case 0xC0 -> GLFW.GLFW_KEY_GRAVE_ACCENT;
            case 0xDB -> GLFW.GLFW_KEY_LEFT_BRACKET;
            case 0xDC -> GLFW.GLFW_KEY_BACKSLASH;
            case 0xDD -> GLFW.GLFW_KEY_RIGHT_BRACKET;
            case 0xDE -> GLFW.GLFW_KEY_APOSTROPHE;

            case 0xA0 -> GLFW.GLFW_KEY_LEFT_SHIFT;
            case 0xA1 -> GLFW.GLFW_KEY_RIGHT_SHIFT;
            case 0xA2 -> GLFW.GLFW_KEY_LEFT_CONTROL;
            case 0xA3 -> GLFW.GLFW_KEY_RIGHT_CONTROL;
            case 0xA4 -> GLFW.GLFW_KEY_LEFT_ALT;
            case 0xA5 -> GLFW.GLFW_KEY_RIGHT_ALT;
            case 0x5B -> GLFW.GLFW_KEY_LEFT_SUPER;
            case 0x5C -> GLFW.GLFW_KEY_RIGHT_SUPER;

            default -> {
                if (vk >= 0x70 && vk <= 0x7B) {
                    yield GLFW.GLFW_KEY_F1 + (vk - 0x70);
                }
                yield GLFW.GLFW_KEY_UNKNOWN;
            }
        };
    }

    private static void gameplayAction(JsonObject message) {
        final long attackSerial =
                message.get("attack").getAsLong();
        final long useSerial =
                message.get("use").getAsLong();
        final boolean attackDown =
                message.get("ad").getAsInt() != 0;
        final boolean useDown =
                message.get("ud").getAsInt() != 0;
        final boolean hostHit =
                message.has("hit")
                && message.get("hit").getAsInt() != 0;

        final double hitX = hostHit
                ? message.getAsJsonArray("p").get(0).getAsDouble()
                : 0.0;
        final double hitY = hostHit
                ? message.getAsJsonArray("p").get(1).getAsDouble()
                : 0.0;
        final double hitZ = hostHit
                ? message.getAsJsonArray("p").get(2).getAsDouble()
                : 0.0;

        final float normalX = hostHit
                ? message.getAsJsonArray("n").get(0).getAsFloat()
                : 0.0f;
        final float normalY = hostHit
                ? message.getAsJsonArray("n").get(1).getAsFloat()
                : 1.0f;
        final float normalZ = hostHit
                ? message.getAsJsonArray("n").get(2).getAsFloat()
                : 0.0f;

        Minecraft client = Minecraft.getInstance();
        client.execute(() -> {
            if (client.player == null
                    || client.level == null
                    || client.gameMode == null
                    || client.screen != null) {
                stopDestroying(client);
                releaseUsing(client);
                return;
            }

            HitResult target = client.hitResult;
            BlockHitResult targetBlock =
                    target instanceof BlockHitResult blockHit
                            && target.getType() == HitResult.Type.BLOCK
                            ? blockHit
                            : null;
            boolean proxyBlockHit =
                    targetBlock != null
                    && Sm64TerrainProxy.isProxy(
                            targetBlock.getBlockPos()
                    );

            if (attackSerial != lastAttackAction && attackDown) {
                lastAttackAction = attackSerial;

                /*
                 * Vanilla always gives visual feedback for a left click,
                 * including a miss. This keeps the real first-person Steve
                 * hand/item animation responsive inside the SM64 window.
                 */
                client.player.swing(InteractionHand.MAIN_HAND);

                if (target instanceof EntityHitResult entityHit) {
                    Entity entity = entityHit.getEntity();
                    client.gameMode.attack(client.player, entity);
                    stopDestroying(client);
                } else if (targetBlock != null && !proxyBlockHit) {
                    startDestroying(client, targetBlock);
                } else {
                    stopDestroying(client);
                }
            }

            if (attackDown && targetBlock != null && !proxyBlockHit) {
                BlockPos pos = targetBlock.getBlockPos();
                Direction face = targetBlock.getDirection();

                /*
                 * When the crosshair moves to another block while the mouse is
                 * held, restart mining exactly like vanilla instead of
                 * continuing an old destroy session against the wrong voxel.
                 */
                if (!destroyingBlock
                        || !pos.equals(destroyingPos)
                        || face != destroyingFace) {
                    startDestroying(client, targetBlock);
                } else {
                    client.gameMode.continueDestroyBlock(pos, face);
                }
            } else if (!attackDown || proxyBlockHit || targetBlock == null) {
                stopDestroying(client);
            }

            if (useSerial != lastUseAction && useDown) {
                lastUseAction = useSerial;

                /*
                 * Vanilla interaction order is important. A block/entity may
                 * return PASS, in which case the held item still gets a chance
                 * to run (food, bows, shields, buckets, etc.). The old bridge
                 * treated any targeted block as "handled" even on PASS.
                 */
                boolean consumed = false;

                if (target instanceof EntityHitResult entityHit) {
                    consumed = tryInteractEntity(client, entityHit);
                }

                if (!consumed && targetBlock != null) {
                    consumed = tryUseOnBlock(client, targetBlock);
                }

                if (!consumed && hostHit) {
                    BlockHitResult synthetic = syntheticSm64Hit(
                            hitX, hitY, hitZ,
                            normalX, normalY, normalZ
                    );
                    consumed = tryUseOnBlock(client, synthetic);
                }

                if (!consumed) {
                    consumed = tryUseInAir(client);
                }

                usingItem = client.player.isUsingItem();

                /*
                 * Some instant-use actions do not enter the using-item state
                 * but still need the normal hand swing.
                 */
                if (consumed && !usingItem) {
                    client.player.swing(InteractionHand.MAIN_HAND);
                }
            }

            if (!useDown) {
                releaseUsing(client);
            }
        });
    }

    private static void startDestroying(
            Minecraft client,
            BlockHitResult hit
    ) {
        BlockPos pos = hit.getBlockPos();
        Direction face = hit.getDirection();

        destroyingBlock = client.gameMode.startDestroyBlock(
                pos,
                face
        );
        destroyingPos = destroyingBlock ? pos.immutable() : null;
        destroyingFace = destroyingBlock ? face : null;
    }

    private static void stopDestroying(Minecraft client) {
        if (destroyingBlock && client.gameMode != null) {
            client.gameMode.stopDestroyBlock();
        }
        destroyingBlock = false;
        destroyingPos = null;
        destroyingFace = null;
    }

    private static void releaseUsing(Minecraft client) {
        if (usingItem
                && client.gameMode != null
                && client.player != null) {
            client.gameMode.releaseUsingItem(client.player);
        }
        usingItem = false;
    }

    private static boolean tryInteractEntity(
            Minecraft client,
            EntityHitResult hit
    ) {
        for (InteractionHand hand : InteractionHand.values()) {
            InteractionResult result = client.gameMode.interact(
                    client.player,
                    hit.getEntity(),
                    hand
            );
            if (result.consumesAction()) {
                client.player.swing(hand);
                return true;
            }
        }
        return false;
    }

    private static boolean tryUseOnBlock(
            Minecraft client,
            BlockHitResult hit
    ) {
        for (InteractionHand hand : InteractionHand.values()) {
            InteractionResult result = client.gameMode.useItemOn(
                    client.player,
                    hand,
                    hit
            );
            if (result.consumesAction()) {
                client.player.swing(hand);
                return true;
            }
        }
        return false;
    }

    private static boolean tryUseInAir(Minecraft client) {
        for (InteractionHand hand : InteractionHand.values()) {
            InteractionResult result = client.gameMode.useItem(
                    client.player,
                    hand
            );
            if (result.consumesAction()) {
                client.player.swing(hand);
                return true;
            }
        }
        return false;
    }

    private static BlockHitResult syntheticSm64Hit(
            double hitX,
            double hitY,
            double hitZ,
            float normalX,
            float normalY,
            float normalZ
    ) {
        /*
         * Convert the native SM64 triangle hit into the hidden overlay world's
         * block grid. Offset outward so a BlockItem sees the voxel immediately
         * outside the original SM64 surface.
         */
        double placeX = hitX + normalX * 0.55;
        double placeY = Sm64VisualSync.renderY(
                hitY + normalY * 0.55
        );
        double placeZ = hitZ + normalZ * 0.55;

        BlockPos placePos = BlockPos.containing(
                placeX,
                placeY,
                placeZ
        );
        Direction face = Direction.getNearest(
                normalX,
                normalY,
                normalZ
        );

        return new BlockHitResult(
                new Vec3(placeX, placeY, placeZ),
                face,
                placePos,
                false
        );
    }

    private static double clamp01(double value) {
        return Math.max(0.0, Math.min(1.0, value));
    }
}
